services:
  - type: cron
    name: google-jobs-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash run.sh
    schedule: "0 9 * * *" # Runs every day at 09:00 UTC (Adjust as needed)
    plan: free
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data_storage # This is where the disk will live
      sizeGB: 1
    envVars:
      # Render will prompt you for these when you create the Blueprint
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
